- data-gathering/github_repos.json
- docs/notebooks/github_repos.json
This PR adds the open source project/community Caluma (https://caluma.io/).
> Add Caluma community

- data-gathering/github_repos.json
- docs/notebooks/github_repos.json
@hazelfire is a development & prototyping company in Zurich that has a couple of repos.
> feat: add hazelfire

- data-gathering/github_repos.json
- docs/notebooks/github_repos.json
Is adding the CSCS like so ok or would it make more sense to put it in universities?
There are a bunch of other `eth-*` orgas (ie. @SwissDataScienceCenter & @ethz-asl) that I'd like to add as well... Maybe a `Universities_Federal` category would make sense?
I'll rebase this PR if you'd rather go in that direction. Let me know how you'd prefer ETH stuff to be added.
> feat: add Swiss National Supercomputing Center

- data-gathering/github_repos.json
- docs/notebooks/github_repos.json
`ResearchAndEducation` fits nicely for this one as well... Thanks @maemst!
> feat: add Fondation Campus Biotech Geneva

- data-gathering/github_repos.json
The Amt für Geoinformation des Kantons Bern @AGIBE has some repos in their own orga and I'm adding those to Kanton Bern.
> feat: add Amt für Geoinformation des Kantons Bern

- data-gathering/github_repos.json
cividi provides urban planning solutions and they are based in switzerland.
> feat: add cividi

- data-gathering/github_repos.json
I'm putting this in "Banking" for now but will raise an issue to talk about renaming "Banking" to "BankingAndFinance".
> feat: add Datatrans AG

- data-gathering/github_repos.json
@antistatique is a web agency from Lausanne/Geneva.
> feat: add antistatique

- data-gathering/github_repos.json
Currently running open source challenge
> feat: add open-sourcechallenge

- data-gathering/github_repos.json
fun fact: novu are the downstairs neighbours of @adfinis-sygroup in Berne
we should probably get some kind of meetup thing going after the pandemic ;)
> feat: novu

- data-gathering/github_repos.json
https://github.com/projectsyn is a VSHN product
> Add projectsyn to vshn org

- data-gathering/github_repos.json
Should there be a comms sector?
> feat: Init7

- data-gathering/github_repos.json
OPTEN are a web agency in Zürich.
> feat: add OPTEN

- data-gathering/github_repos.json
The ITU is headquartered in Geneva.
> feat: add International Telecommunication Union

- data-gathering/github_repos.json
The World Health Organization is headquartered in Geneva.
> feat: add World Health Organization

- data-gathering/github_repos.json
Fixed as per https://github.com/digital-sustainability/oss-github-benchmark/pull/20#issuecomment-745680768
> fix: s/hazelfire/hzlf/

- frontend/src/app/ranking/ranking.component.ts
Made number in title responsive to filter changes.
> Institution count in title

- data-gathering/OSS_github_benchmark.py
Check for already running action and wait if found.
> Already running action 

- frontend/src/app/dimension-selector/dimension-selector.component.ts
- frontend/src/app/explore/explore-item/explore-item.component.ts
- frontend/src/app/pipes/toNiceName.pipe.ts
- frontend/src/app/repository-detail-view/repository-detail-view.component.ts
removed uuid from institutions + repo detail view with some minor refactorings
> removed uuid from institutions + repo detail view

- data-gathering/github_repos.json
SIARD Suite is a software developed by the Federal Archives to simplify archiving of relational databases. It complies with international standards and is used in over 50 countries around the globe. It is provided by the Federal Archives free of charge.
> Add sfa-siard

- data-gathering/github_repos.json
I stumbled over greenpeace recently.
I just generated a new uuid, let me know if this is wrong and needs to be updated or if there are any other changes i should take care of.
> feat: add GreenpeaceSchweiz

- data-gathering/github_repos.json
I have generated a version 4 UUID, hope that fits.
> Add Ops One AG

- data-gathering/github_repos.json
I'm not 100% convinced that NGOs is the right category but it seems like the closest match. Let me know if you'd like me to change anything. Thanks.
> feat: add spschweiz

- data-gathering/github_repos.json
> feat: add Inventage AG

- .gitlab-ci.yml
> Updated gitlab pipeline file.

- oss-api/src/github-crawler/github-crawler.service.ts
> Fixxed Build error

- githubRepoValidation.py
feat: Added github repo file validation script
> Adding validation pipeline

- .github/workflows/ci.yaml
- .github/workflows/validate_configs.yaml
Fixes https://github.com/digital-sustainability/oss-github-benchmark/issues/272
> Validate `github_repos.json` in Continuous Integration

- .github/workflows/validate_configs.yaml
https://github.com/digital-sustainability/oss-github-benchmark/issues/272
> Fix typo in validate_configs action

- github_repos.json
> Updating github repos file

- Contributing.md
- frontend/src/app/pipes/toNiceName.pipe.ts
Updated Contributing.md to include political parties and better explain how to contribute.
Also updated custom angular pipes to include the new political parties
See https://github.com/digital-sustainability/oss-github-benchmark/issues/264
> Updated Contributing.md and custom pipe

- github_repos.json
Removing fcbg institution.
see https://github.com/digital-sustainability/oss-github-benchmark/issues/302
> Removing old institution

- frontend/src/app/institution-detail-view/institution-detail-view.component.ts
Updated Institution detail view with the new Information 
see: https://github.com/digital-sustainability/oss-github-benchmark/issues/304
> Updating Institution Detail View

- frontend/src/app/data.service.ts
- frontend/src/app/institution-detail-view/institution-detail-view.component.ts
- oss-api/src/api/api.controller.ts
Added new Endpoint for the repositories in the institution detail view as the repos were filtered with full text search instead of only filtering the institutions
see https://github.com/digital-sustainability/oss-github-benchmark/issues/311
> Adding new endpoint for the institution detail view

- github_repos.json
- chili-epfl
- cvlab-epfl
- dedis
- DESL-EPFL
- dslab-epfl
- epfl-dojo
- EPFL-ENAC
- epfl-exts
- epfl-ic
- epfl-lasa
- epfl-mades
- epfl-ml4ed
- epfl-scitas
- epfl-SDP
- epfl-si
- epfllibrary
- GameLab-UNIL-EPFL
- lampepfl
- lbnc-epfl
- lsmo-epfl
- PolyLAN
> Add some of EPFL repositories

- github_repos.json
I stumbled over some orgs for Uni Zürich :)
> feat(UZH): add some orgs for Uni Zürich

- github_repos.json
> feat: add Swiss Institute of Bioinformatics (SIB)

- github_repos.json
Natron are a start up in Bern https://natron.io/
> feat: add Natron

- frontend/angular.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/add-institution/add-institution.component.html
- frontend/src/app/add-institution/add-institution.component.scss
- frontend/src/app/add-institution/add-institution.component.ts
- frontend/src/app/app.module.ts
- frontend/src/app/authentication.service.ts
- frontend/src/app/data.service.ts
- frontend/src/app/nav/nav.component.html
- github_repos.json
- oss-api/src/api/api.controller.ts
- oss-api/src/auth/auth.controller.ts
- oss-api/src/auth/auth.guard.ts
- oss-api/src/auth/auth.module.ts
- oss-api/src/auth/auth.service.ts
- oss-api/src/auth/constants.ts
- oss-api/src/mongo-db/mongo-db.service.ts
- package-lock.json
- package.json
Improved features for adding and editing Institutions which are to be added to the List of Institutions.
> Todo inst display

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/add-institution/add-institution.component.html
- frontend/src/app/add-institution/add-institution.component.ts
- frontend/src/app/data.service.ts
- frontend/src/app/ranking/ranking.component.html
- frontend/src/app/ranking/ranking.component.ts
- frontend/src/app/repositories-ranking/repositories-ranking.component.html
- frontend/src/app/repositories-ranking/repositories-ranking.component.ts
- frontend/src/app/services/data-export.service.spec.ts
- frontend/src/app/services/data-export.service.ts
- frontend/src/app/user-ranking/user-ranking.component.html
- frontend/src/app/user-ranking/user-ranking.component.ts
- oss-api/src/api/api.controller.ts
- oss-api/src/api/dto/institution-query.dto.ts
- oss-api/src/api/dto/repository-query.dto.ts
- oss-api/src/auth/add-institution/add-institution.module.ts
- oss-api/src/auth/auth.guard.spec.ts
- oss-api/src/auth/auth.module.ts
- oss-api/src/auth/constants.ts
- oss-api/src/mongo-db/mongo-db.service.spec.ts
- oss-api/src/mongo-db/mongo-db.service.ts
New feature: Data Export for logged in user
> Data export feature 

- github_repos.md
* https://github.com/kiwix
* https://github.com/openzim
* https://github.com/offspot
More information about Kiwix at https://kiwix.org
> Update github_repos.md with 3 Kiwix GitHub orgs
